### ISSUE TITLE
No resource type found for:v1beta1#Component  at [Source: N/A; line: -1, column: -1] 

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#24]
### Description

When we test this class : https://github.com/ap4k/ap4k/blob/issue-20/examples/component-example/src/test/java/io/ap4k/examples/ComponentSpringBootExampleTest.java
then we got this error

### Error

```
io.ap4k.Ap4kException: No resource type found for:v1beta1#Component
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.ap4k.deps.kubernetes.api.model.KubernetesList["items"]->java.util.ArrayList[0])

	at io.ap4k.Ap4kException.launderThrowable(Ap4kException.java:26)
	at io.ap4k.Ap4kException.launderThrowable(Ap4kException.java:16)
	at io.ap4k.utils.Serialization.unmarshal(Serialization.java:97)
	at io.ap4k.utils.Serialization.unmarshal(Serialization.java:72)
	at io.ap4k.utils.Serialization.unmarshal(Serialization.java:61)
	at io.ap4k.examples.ComponentSpringBootExampleTest.shouldContainComponent(ComponentSpringBootExampleTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:436)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:112)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: io.ap4k.deps.jackson.databind.JsonMappingException: No resource type found for:v1beta1#Component
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.ap4k.deps.kubernetes.api.model.KubernetesList["items"]->java.util.ArrayList[0])
	at io.ap4k.deps.jackson.databind.JsonMappingException.from(JsonMappingException.java:255)
	at io.ap4k.deps.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:982)
	at io.ap4k.deps.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78)
	at io.ap4k.deps.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
	at io.ap4k.deps.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at io.ap4k.deps.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	at io.ap4k.deps.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	at io.ap4k.deps.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at io.ap4k.deps.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at io.ap4k.deps.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at io.ap4k.deps.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at io.ap4k.deps.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3779)
	at io.ap4k.deps.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2050)
	at io.ap4k.deps.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2547)
	at io.ap4k.deps.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:80)
	at io.ap4k.deps.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
	at io.ap4k.deps.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1578)
	at io.ap4k.deps.jackson.databind.ObjectReader.readValue(ObjectReader.java:1166)
	at io.ap4k.utils.Serialization.unmarshal(Serialization.java:95)
```

**Comment by cmoulliard** [comment]
Problem fixed by PR #49
