### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: io.ap4k.deps.openshift.api.model.BuildSpec

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#7]
This error is reported if I change the version of the ap4k deps to use `1.0-SNAPSHOT`
and execute `mvn clean install`

```
[INFO] --- maven-install-plugin:2.4:install (default-install) @ ap4k-micronaut ---
[INFO] Installing /Users/dabou/Code/snowdrop/ap4k/ap4k-annotations/frameworks/micronaut/target/ap4k-micronaut-1.0-SNAPSHOT.jar to /Users/dabou/.m2/repository/io/ap4k/ap4k-micronaut/1.0-SNAPSHOT/ap4k-micronaut-1.0-SNAPSHOT.jar
[INFO] Installing /Users/dabou/Code/snowdrop/ap4k/ap4k-annotations/frameworks/micronaut/pom.xml to /Users/dabou/.m2/repository/io/ap4k/ap4k-micronaut/1.0-SNAPSHOT/ap4k-micronaut-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] AP4K 1.0-SNAPSHOT .................................. SUCCESS [  0.306 s]
[INFO] AP4K :: Core ....................................... SUCCESS [ 13.281 s]
[INFO] AP4K :: Annotations ................................ SUCCESS [  0.011 s]
[INFO] AP4K :: Annotations :: Kubernetes .................. SUCCESS [  3.253 s]
[INFO] AP4K :: Annotations :: Openshift ................... SUCCESS [  7.634 s]
[INFO] AP4K :: Annotations :: Istio ....................... SUCCESS [  4.190 s]
[INFO] AP4K :: Annotations :: Service Catalog ............. SUCCESS [  4.754 s]
[INFO] AP4K :: Annotations :: Component Operator .......... SUCCESS [  6.043 s]
[INFO] AP4K :: Frameworks ................................. SUCCESS [  0.013 s]
[INFO] AP4K :: Frameworks :: Spring Boot .................. SUCCESS [  1.701 s]
[INFO] AP4K :: Examples ................................... SUCCESS [  0.008 s]
[INFO] AP4K :: Examples :: Service Catalog ................ SUCCESS [  1.211 s]
[INFO] AP4K :: Examples :: Kubernetes ..................... SUCCESS [  2.825 s]
[INFO] AP4K :: Examples :: Openshift ...................... SUCCESS [  3.932 s]
[INFO] AP4K :: Examples :: Istio .......................... SUCCESS [  1.298 s]
[INFO] AP4K :: Examples :: Spring Boot on Kubernetes ...... SUCCESS [  2.922 s]
[INFO] AP4K :: Examples :: Spring Boot on Openshift ....... SUCCESS [  3.164 s]
[INFO] AP4K :: Examples :: Component Operator ............. SUCCESS [  0.856 s]
[INFO] AP4K :: Testing .................................... SUCCESS [  0.007 s]
[INFO] AP4K :: Testing :: Openshift ....................... SUCCESS [  0.890 s]
[INFO] AP4K :: Examples :: Source to Image Example ........ SUCCESS [ 54.237 s]
[INFO] AP4K :: Frameworks :: Thorntail .................... SUCCESS [  0.557 s]
[INFO] AP4K :: Frameworks :: Micronaut 1.0-SNAPSHOT ....... SUCCESS [  0.489 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:53 min
[INFO] Finished at: 2018-11-21T18:18:12+01:00
[INFO] ------------------------------------------------------------------------
Applied: s2i-java
Applied: source-to-image-example
Applied: source-to-image-example
Applied: source-to-image-example
Exception in thread "Thread-35" java.lang.NoClassDefFoundError: Lio/ap4k/deps/openshift/api/model/BuildSpec;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.getDeclaredFields(Class.java:1916)
        at io.ap4k.deps.jackson.databind.util.ClassUtil$ClassMetadata.getDeclaredFields(ClassUtil.java:1087)
        at io.ap4k.deps.jackson.databind.util.ClassUtil.getDeclaredFields(ClassUtil.java:386)
        at io.ap4k.deps.jackson.databind.introspect.AnnotatedClass._findFields(AnnotatedClass.java:809)
        at io.ap4k.deps.jackson.databind.introspect.AnnotatedClass.resolveFields(AnnotatedClass.java:575)
        at io.ap4k.deps.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:353)
        at io.ap4k.deps.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:350)
        at io.ap4k.deps.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:283)
        at io.ap4k.deps.jackson.databind.introspect.POJOPropertiesCollector.getPropertyMap(POJOPropertiesCollector.java:248)
        at io.ap4k.deps.jackson.databind.introspect.POJOPropertiesCollector.getProperties(POJOPropertiesCollector.java:155)
        at io.ap4k.deps.jackson.databind.introspect.BasicBeanDescription._properties(BasicBeanDescription.java:142)
        at io.ap4k.deps.jackson.databind.introspect.BasicBeanDescription.findProperties(BasicBeanDescription.java:217)
        at io.ap4k.deps.jackson.databind.deser.BasicDeserializerFactory._findCreatorsFromProperties(BasicDeserializerFactory.java:330)
        at io.ap4k.deps.jackson.databind.deser.BasicDeserializerFactory._constructDefaultValueInstantiator(BasicDeserializerFactory.java:312)
        at io.ap4k.deps.jackson.databind.deser.BasicDeserializerFactory.findValueInstantiator(BasicDeserializerFactory.java:252)
        at io.ap4k.deps.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:221)
        at io.ap4k.deps.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:143)
        at io.ap4k.deps.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:406)
        at io.ap4k.deps.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
        at io.ap4k.deps.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at io.ap4k.deps.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at io.ap4k.deps.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at io.ap4k.deps.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477)
        at io.ap4k.deps.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3908)
        at io.ap4k.deps.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3803)
        at io.ap4k.deps.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2874)
        at io.ap4k.deps.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:235)
        at io.ap4k.deps.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:190)
        at io.ap4k.deps.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:383)
        at io.ap4k.deps.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:360)
        at io.ap4k.deps.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromInputStream(BuildConfigOperationsImpl.java:274)
        at io.ap4k.deps.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromFile(BuildConfigOperationsImpl.java:231)
        at io.ap4k.deps.openshift.client.dsl.internal.BuildConfigOperationsImpl.fromFile(BuildConfigOperationsImpl.java:68)
        at io.ap4k.openshift.hook.JavaBuildHook.run(JavaBuildHook.java:70)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.ap4k.deps.openshift.api.model.BuildSpec
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 37 more

```

**Comment by iocanel** [comment]
The maven build no longer performs an s2i build by default. It has to be explicitly specified.
